name: kid_upp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0 #Service locator
  flutter_bloc: ^8.1.1 #Bloc for state management
  equatable: ^2.0.5 #Value equality
  dartz: ^0.10.1 #Functional programming thingies
  shared_preferences: ^2.0.15 #Local cache 
  responsive_framework: ^0.2.0
  flutter_keyboard_visibility: ^5.4.0
  flutter_localizations: 
      sdk: flutter
  intl: ^0.17.0
  fluttertoast: ^8.1.1
  #Firebase
  cloud_firestore: ^4.1.0
  firebase_storage: ^11.0.6
  firebase_auth: ^4.1.5
  firebase_core: ^2.3.0
  cupertino_icons: ^1.0.2
  mask_text_input_formatter: ^2.4.0
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter  
  mockito: ^5.3.2
  

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
      - assets/images/wallpaper.jpg
      - assets/images/wallpaper2.jpg
      - assets/images/amblem.jpg
      - assets/images/upperwallpaper.jpg
      - assets/images/announcement.png
      - assets/images/instagram.png
      - assets/images/profile_photo.png
      - assets/images/schedule.png
      - assets/images/mealmenu.png
      - assets/images/photogalery.png
      - assets/images/medicine.png
      - assets/images/pays.png
      - assets/images/activity.png
      - assets/images/endofday.png
      - assets/images/requirementlist.png
      - assets/images/options.png
      - assets/images/classinfo.png
      - assets/images/newmessage.png
      - assets/images/home.png
      - assets/images/customer.png
      
  
